#!/bin/bash

# Directorio donde se encuentran las baterías
dir="/sys/class/power_supply/"

# Inicializar un array vacío para almacenar la información de las baterías
json='[]'

# Recorrer todos los archivos en el directorio de las baterías
for file in $(ls $dir); do
 # Comprobar si el archivo es una batería
 if [[ $file =~ ^BAT[0-9]+$ ]]; then
    # Obtener la ruta completa al archivo de la batería
    bat="${dir}${file}"
    # Comprobar si el archivo existe
    if [ -d $bat ]; then
      # Obtener el porcentaje de la batería
      per=$(cat "$bat/capacity")
      # Obtener el estado de la batería en minusculas
      sta=$(cat "$bat/status" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
      # Crear un nuevo objeto para la batería
      bat_info="{\"charge\": $per, \"status\": \"$sta\"}"
      # Añadir la información de la batería al array JSON
      json=$(echo $json | jq --argjson bat_info "$bat_info" '. + [$bat_info]')
    fi
 fi
done

# Imprimir el objeto JSON en una sola línea
echo "$json"
