#!/bin/sh

LANG=en

status() {
  if [[ $(nmcli networking connectivity) = "full" ]]; then
    echo "connected"
  else
    echo "disconnected"
  fi
}

symbol() {
  st=$(nmcli networking connectivity)
  if [[ $st = "full" ]]; then
    echo 󰤨
    return 0
  elif [[ $st = "none" ]]; then
    echo 󰤯
  else
    echo 󰤩
  fi

  return 1
}

name() {
  if [[ $(nmcli networking connectivity) = "full" ]]; then
    echo $(nmcli -t -f GENERAL.CONNECTION,GENERAL.DEVICE dev show | head -n 1 | cut -d':' -f2)
  fi
}

echo "{ \"status\": \"$(status)\", \"network\": \"$(name)\", \"icon\": \"$(symbol)\" }"

exit
